name = "gleam_javascript"
version = "0.1.0"
licences = ["Apache-2.0"]
description = "Work with JavaScript types and values in Gleam"

target = "javascript"

repository = { type = "github", user = "gleam-lang", repo = "javascript" }
links = [
  { title = "Website", href = "https://gleam.run" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.19"

[dev-dependencies]
gleeunit = "~> 0.6"
